# list =[1,9,3,4,8,6,7]
# # list.append(9)
# # print(list)
# # list.sort()
# # print(list)
# # list.sort(reverse=True)
# # print(list)
# # list.reverse()
# # print(list)
# # list.insert(3,5)
# # print(list)
# # list.pop(3)
# # print(list)
# # list.extend()
# print(list)
# print(type(list))
# print(list[0])
# print(len(list))
tuple=(2,3,4,5,6,7,8,9)
# print(type(tuple))
# print(len(tuple))
tuple.index(3)
print(tuple)


